In [1]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("wordnet")
nltk.download('stopwords')

[nltk_data] Downloading package punkt to C:\Users\Sajib
[nltk_data]     Saha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Sajib
[nltk_data]     Saha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Sajib
[nltk_data]     Saha\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Sajib
[nltk_data]     Saha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
df = pd.read_csv("Twitter_Data.csv")

In [3]:
df.head()

                                          clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [6]:
df.isna().sum()

clean_text    4
category      7
dtype: int64

In [7]:
df.shape

(162980, 2)

In [8]:
df= df.dropna()

In [9]:
import re

# stopwords
stop_w = set(stopwords.words('english'))

# lemmatizer
lemmatizer = WordNetLemmatizer()

def text_preprocessing(phrase): # class e convert kore niben

    # lowercase
    phrase = phrase.lower()

    # contractions
    phrase = re.sub(r"won't", "will not", phrase)
    phrase = re.sub(r"can't", "can not", phrase)

    # general contractions
    phrase = re.sub(r"n't", " not", phrase)
    phrase = re.sub(r"'re", " are", phrase)
    phrase = re.sub(r"'s", " is", phrase)
    phrase = re.sub(r"'d", " would", phrase)
    phrase = re.sub(r"'ll", " will", phrase)
    phrase = re.sub(r"'ve", " have", phrase)
    phrase = re.sub(r"'m", " am", phrase)

    # custom replacement
    phrase = re.sub(r"luv", "love", phrase)

    # remove emoji, punctuation, digits
    phrase = re.sub(r"[^a-zA-Z\s]", " ", phrase)

    # remove extra spaces
    phrase = re.sub(r"\s+", " ", phrase).strip()

    # tokenize
    words = phrase.split()

    # stopword removal + lemmatization
    words = [
        lemmatizer.lemmatize(word.lower())
        for word in words
        if word not in stop_w
    ]

    return " ".join(words)

# apply
df["text"] = df["clean_text"].apply(text_preprocessing)

In [10]:
df.head()

,clean_text,category,text
0,when modi promised “minimum government maximum...,-1.0,modi promised minimum government maximum gover...
1,talk all the nonsense and continue all the dra...,0.0,talk nonsense continue drama vote modi
2,what did just say vote for modi welcome bjp t...,1.0,say vote modi welcome bjp told rahul main camp...
3,asking his supporters prefix chowkidar their n...,1.0,asking supporter prefix chowkidar name modi gr...
4,answer who among these the most powerful world...,1.0,answer among powerful world leader today trump...

In [25]:
x = df[["text"]]
y = df[["category"]]

In [26]:
split_range= .80
len_x = len(x)
split_num = int(split_range*len_x)
train_text = x[:split_num]
train_label = y[:split_num]

test_text = x[split_num:]
test_label= y[split_num:]

In [27]:
test_text

                                                     text
130376  pradhan mantri mudra yojana crore people got m...
130377                               modi everywhere like
130378  modi gatbandhan cbi medium calling name genuin...
130379  attacking congress modi said grand old party s...
130380  ill chowkidaar power modi realized chowkidaar ...
...                                                   ...
162975  crore paid neerav modi recovered congress lead...
162976  dear rss terrorist payal gawar modi killing pl...
162977                       cover interaction forum left
162978  big project came india modi dream project happ...
162979  ever listen like gurukul discipline maintained...

[32594 rows x 1 columns]

In [28]:
test_label

        category
130376      -1.0
130377       0.0
130378       1.0
130379       1.0
130380      -1.0
...          ...
162975      -1.0
162976      -1.0
162977       0.0
162978       0.0
162979       1.0

[32594 rows x 1 columns]

In [29]:
from gensim.models import Word2Vec, KeyedVectors

embedding_size= 256
model = Word2Vec(train_label, vector_size= embedding_size, window=7, min_count=1, workers=4)

In [30]:
import numpy as np

def getVectors(dataset):
    vectors = []

    for dataItem in dataset:
        singleDataItemEmbedding = np.zeros(embedding_size)
        wordCount = 0

        for word in dataItem:
            if word in model.wv.key_to_index:
                singleDataItemEmbedding += model.wv[word]
                wordCount += 1

        if wordCount > 0:
            singleDataItemEmbedding /= wordCount

        vectors.append(singleDataItemEmbedding)

    return np.array(vectors)


trainReviewVectors = getVectors(train_text)
testReviewVectors = getVectors(test_text)

In [31]:
trainReviewVectors

array([[-3.10108097e-03,  2.08082547e-03, -1.70587096e-04,
         2.12822901e-03, -4.95505519e-04,  3.77608618e-04,
         1.51215432e-03, -9.58851073e-04, -1.15663745e-04,
         1.42380176e-03,  1.51865355e-03, -6.02365471e-05,
         1.98952435e-03, -2.23457441e-03,  5.41443005e-05,
         8.82982276e-05,  2.07017936e-03,  1.48348200e-03,
         9.59355850e-04,  3.00509591e-03, -3.33225681e-03,
         1.54754799e-03, -2.38263762e-03, -8.86252150e-04,
        -2.27194466e-03, -1.20249375e-03, -2.78298091e-03,
        -2.19306163e-03, -2.14473112e-03, -7.68431152e-05,
        -9.02705515e-04,  1.59608666e-03, -3.18770794e-03,
        -1.60680929e-03,  3.38010692e-03,  2.30715067e-03,
         8.42523761e-04,  6.58323988e-04,  4.38579048e-04,
        -1.27920151e-03,  3.35097158e-04,  1.28140983e-03,
         8.77847585e-04,  7.03205355e-04,  2.52190791e-03,
         1.80258524e-03, -2.11289572e-03, -6.01213425e-04,
        -1.17079820e-04,  2.89075930e-03,  2.14305598e-03,
         2.71897608e-03,  2.73805903e-03, -2.52612230e-03,
         1.28139167e-03, -2.19605553e-04, -1.62863359e-03,
         3.51417655e-03,  1.24855619e-03,  3.28063654e-04,
        -1.92430910e-03, -5.39340079e-04,  5.98254924e-04,
         1.60323316e-03,  9.76513450e-05, -1.34005599e-03,
         4.95646770e-05,  1.07354950e-04,  1.42276598e-03,
         1.22035854e-05, -7.65801718e-04,  2.34120370e-04,
        -6.16498912e-04, -1.75943598e-04,  1.23623914e-04,
        -3.26656581e-04,  2.53316884e-03,  7.11077514e-04,
        -5.57202380e-04,  2.67902001e-03,  1.49730810e-03,
         9.07797056e-04,  9.90004589e-04,  3.09680682e-03,
         1.34539496e-03, -8.01671917e-04,  2.91922937e-03,
         1.55163215e-03,  1.17620981e-03, -7.35561519e-04,
         2.51053988e-04, -1.89654032e-03, -2.63894489e-03,
        -5.36938508e-05,  1.76194698e-03,  1.20553250e-03,
        -1.08782528e-03,  4.76703824e-04,  1.16708657e-03,
        -2.24090197e-03, -7.59219751e-04, -2.48403599e-03,
         1.25587483e-03,  2.28468779e-03,  1.32206051e-03,
         1.11475307e-03,  1.86931233e-03,  9.26529833e-04,
        -1.47594760e-04, -1.77677659e-03,  2.20788596e-03,
         1.99476086e-03,  5.53030521e-04, -3.59784346e-04,
        -2.57646323e-03, -1.94485082e-03,  1.16054962e-03,
        -9.87273175e-04, -1.41367208e-03,  3.53610454e-03,
         1.74868045e-03,  2.07239483e-03,  1.53101018e-03,
        -2.15761131e-03,  1.88092592e-03,  1.57862746e-04,
         1.84522786e-03,  4.47810783e-04,  3.38124949e-03,
        -1.83292214e-03,  1.47947172e-03, -2.45914453e-03,
        -1.69022630e-03, -1.62200925e-03, -1.66821278e-03,
         1.55354974e-03,  2.61424296e-03, -7.55668152e-04,
         1.12486041e-03, -1.28706886e-03,  1.27306736e-03,
         2.48134571e-03,  9.87993864e-04,  1.35287487e-04,
        -3.00097124e-03,  1.58511164e-03, -8.51568766e-05,
         5.72139708e-04,  2.41919033e-03, -4.50275528e-04,
        -2.07192156e-03,  2.73116709e-04, -7.15233851e-04,
        -7.01054465e-04, -1.74272836e-03, -2.80747920e-03,
         2.13525475e-03,  3.20073093e-03, -9.69671489e-04,
         1.63328213e-03,  2.98210637e-03, -2.11314609e-04,
         9.02241562e-04,  1.48635668e-04,  2.48620830e-03,
         2.72598413e-03, -6.12654413e-04, -9.93895034e-04,
        -9.79345447e-04,  1.59626299e-03,  1.79286627e-03,
         5.93589308e-04,  1.70307079e-04, -2.58460377e-03,
        -1.47129906e-03, -2.18601959e-03,  2.26805064e-03,
         6.17926785e-04,  1.27458277e-03, -1.39684416e-04,
        -1.40733256e-03, -9.35563042e-04,  6.17646457e-04,
         2.87452728e-03,  2.31576944e-03,  8.54297075e-04,
        -1.30120618e-03, -1.74963955e-03, -9.74028837e-04,
        -1.22872895e-03, -2.16508284e-03, -3.11481782e-03,
         1.80390477e-03,  1.05987303e-04,  3.42836448e-04,
        -2.37480473e-03,  1.85177987e-03,  3.88783092e-04,
         5.11814530e-04,  1.70577224e-03, -1.89963356e-03,
         1.36838946e-03, -3.00962167e-04, -1.13288049e-03,
         1.04462169e-03,  1.76666289e-03,  9.60805764e-04,
         1.54752377e-03, -6.51946136e-04, -1.85935789e-03,
         1.18348608e-03, -7.08935938e-04,  4.08106018e-04,
         6.26437987e-04,  7.47172628e-04, -1.53343178e-03,
        -2.37725365e-04,  3.08030751e-03, -1.91051932e-03,
         2.28245479e-03, -3.03156891e-03, -1.90056240e-04,
         1.72867021e-03,  1.18847548e-03, -2.10306359e-03,
        -5.11625626e-04, -7.19577384e-04, -3.03263466e-05,
        -1.04676637e-03,  1.43714792e-03, -9.02384209e-04,
        -2.92970302e-03, -1.70227978e-03,  1.95555296e-03,
        -5.31389378e-04, -4.94135854e-04, -3.16222385e-03,
         8.36252390e-04,  1.90045840e-03,  1.00079924e-03,
        -1.37150427e-03,  1.64851484e-03, -3.62569001e-04,
        -6.59234201e-04, -2.78526063e-03, -4.98633211e-05,
         2.85206052e-04,  3.02789857e-03,  5.53079726e-04,
        -2.96886607e-03, -1.46209511e-03, -1.79782417e-03,
         1.29642679e-03,  1.41558672e-03, -2.55863291e-03,
         2.18682317e-03]])